name: TWRP CI

on:
  push:
    branches: [ android-4.4 ]
  pull_request:
    branches: [ android-4.4 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test all cores
      run: echo $(nproc --all)
