name: TWRP CI

on:
  push:
    branches: [ android-4.4 ]
  pull_request:
    branches: [ android-4.4 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing JDK 7
      run: |
        mkdir ~/.jdk_7
        cd ~/.jdk_7
        wget https://repo.huaweicloud.com/java/jdk/7u80-b15/jdk-7u80-linux-i586.tar.gz
        tar -xzf jdk-7u80-linux-i586.tar.gz

    - name: Syncing TWRP sources
      run: |
        mkdir ~/TWRP
        cd ~/TWRP

        CORES_USED=$(nproc --all)
        repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-4.4-deprecated
        repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$CORES_USED

        for i in device; do
          rm -rf $i/samsung/goya
          git clone --single-branch git://github.com/TriDiscord/twrp_$i\_samsung_goya.git $i/samsung/goya
        done
  
    - name: Building TWRP
      run: |
        export PATH="$HOME/.jdk_7/jdk1.7.0_80/bin:$PATH"
        export JAVA_HOME="$HOME/.jdk_7/jdk1.7.0_80"

        cd ~/TWRP
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        lunch omni_goya-eng
        mka recoveryimage
